/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionBuilderModel } from './filterExpressionBuilderModel';
import { FilterExpressionBuilderApiConfig } from './filterExpressionBuilderApiConfig';
import { UiAction } from '../../view/model/uiAction';
import { FilterExpressionField } from './filterExpressionField';
import { FilterExpressionFieldEditor } from './filterExpressionFieldEditor';
import { FilterExpressionFieldList } from './filterExpressionFieldList';


export interface FilterExpressionBuilderUiModel { 
    model?: FilterExpressionBuilderModel;
    selectedField?: FilterExpressionField;
    selectedFieldEditor?: FilterExpressionFieldEditor;
    selectUiAction?: UiAction;
    deselectUiAction?: UiAction;
    possibleActions?: Array<UiAction>;
    showGroups?: boolean;
    readOnly?: boolean;
    extarnalDatabase?: boolean;
    filterGroupsAction?: UiAction;
    groupFilter?: FilterExpressionFieldList;
    groupFilterAction?: UiAction;
    viewUuid?: string;
    config?: FilterExpressionBuilderApiConfig;
    type?: FilterExpressionBuilderUiModel.TypeEnum;
}
export namespace FilterExpressionBuilderUiModel {
    export const TypeEnum = {
        Simple: 'SIMPLE',
        Complex: 'COMPLEX'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


