/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FilterExpressionDataType = {
    String: 'STRING',
    Number: 'NUMBER',
    Date: 'DATE',
    DateTime: 'DATE_TIME',
    Boolean: 'BOOLEAN'
} as const;
export type FilterExpressionDataType = typeof FilterExpressionDataType[keyof typeof FilterExpressionDataType];

