/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FilterExpressionOperation = {
    Expression: 'EXPRESSION',
    Equal: 'EQUAL',
    NotEqual: 'NOT_EQUAL',
    Less: 'LESS',
    LessOrEqual: 'LESS_OR_EQUAL',
    Greater: 'GREATER',
    GreaterOrEqual: 'GREATER_OR_EQUAL',
    Like: 'LIKE',
    NotLike: 'NOT_LIKE',
    Between: 'BETWEEN',
    NotBetween: 'NOT_BETWEEN',
    IsEmpty: 'IS_EMPTY',
    IsNotEmpty: 'IS_NOT_EMPTY',
    Exists: 'EXISTS',
    NotExists: 'NOT_EXISTS',
    In: 'IN',
    NotIn: 'NOT_IN'
} as const;
export type FilterExpressionOperation = typeof FilterExpressionOperation[keyof typeof FilterExpressionOperation];

