/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionDataType } from './filterExpressionDataType';
import { FilterExpressionFieldWidgetType } from './filterExpressionFieldWidgetType';
import { Value } from '../../value/model/value';
import { FilterExpressionData } from './filterExpressionData';
import { FilterExpressionOperation } from './filterExpressionOperation';
import { FilterExpressionFieldList } from './filterExpressionFieldList';


export interface FilterExpressionField { 
    /**
     * The display name of the whole field. Tipically the label of the property we are filtering
     */
    label?: string;
    /**
     * This identifier is unique inside the model let it be a builder model or a normal model object. 
     */
    id?: string;
    label1: string;
    label2?: string;
    label3?: string;
    placeholder1?: string;
    placeholder2?: string;
    placeholder3?: string;
    icon?: string;
    expressionData?: FilterExpressionData;
    possibleOperations?: Array<FilterExpressionOperation>;
    filterFieldType?: FilterExpressionDataType;
    possibleValues: Array<Value>;
    widgetType?: FilterExpressionFieldWidgetType;
    subFieldList?: FilterExpressionFieldList;
    /**
     * Identifier of the toolbar associated with this widget. 
     */
    toolbarId?: string;
}
export namespace FilterExpressionField {
}


