/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionField } from './filterExpressionField';


export interface FilterExpressionFieldList { 
    /**
     * If the field list is included into builder model then this identifier is unique inside the model. 
     */
    id?: string;
    label?: string;
    icon?: string;
    filters: Array<FilterExpressionField>;
}

