/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionField } from './filterExpressionField';


/**
 * The available filter fields contains the pre setup filter field as a template. It can be easily copied and added to the filter field list. 
 */
export interface FilterExpressionBuilderField { 
    label?: string;
    fieldTemplate?: FilterExpressionField;
    /**
     * If less or equal zero then there is no limit how many time we can use the given filter. Else it is the limit where the typical value is 1 becase we can use the given filter field only once. 
     */
    limitOfUsage?: number;
    /**
     * The unique identifiers of fields initiated from this builder field in the workplace.
     */
    instanceIds?: Array<string>;
}

