/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionBuilderModel } from './filterExpressionBuilderModel';


export interface FilterExpressionBuilder { 
    uri?: string;
    data?: FilterExpressionBuilderModel;
}

