/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmartLayoutDefinition } from '../../form/model/smartLayoutDefinition';
import { UiAction } from '../../view/model/uiAction';


export interface FilterExpressionFieldEditor { 
    layoutDef?: SmartLayoutDefinition;
    possibleActions?: Array<UiAction>;
}

