/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionBuilderGroup } from './filterExpressionBuilderGroup';
import { FilterExpressionList } from './filterExpressionList';
import { FilterExpressionFieldList } from './filterExpressionFieldList';


/**
 * The filter field model data contains a list of groups that form a tree structure for the available filter fields. It contains the groups of available fields and the workplace root list that conatins the already added filters. On the builder side  we refer the unique identifiers of the field lists and fields. 
 */
export interface FilterExpressionBuilderModel { 
    label?: string;
    /**
     * This is the group of filter expressions that can be involved to the workplace. This is a tree structure.
     */
    groups?: Array<FilterExpressionBuilderGroup>;
    exceptionalGroup?: FilterExpressionBuilderGroup;
    workplaceList?: FilterExpressionFieldList;
    defaultFilters?: FilterExpressionList;
}

