/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionData } from './filterExpressionData';


/**
 * The filter expressions can be gathered into a list. In case of a plain filter expression this is the root object of the expression list. 
 */
export interface FilterExpressionList { 
    expressions: Array<FilterExpressionData>;
}

