/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionBoolOperator } from './filterExpressionBoolOperator';
import { FilterExpressionList } from './filterExpressionList';
import { FilterExpressionOperation } from './filterExpressionOperation';
import { FilterExpressionOperandData } from './filterExpressionOperandData';


/**
 * The expression data is the decriptor of an expression stands for an equal, like etc. and also can be a bracket where  we have embedded expressions. 
 */
export interface FilterExpressionData { 
    operand1?: FilterExpressionOperandData;
    operand2?: FilterExpressionOperandData;
    operand3?: FilterExpressionOperandData;
    currentOperation?: FilterExpressionOperation;
    modifier?: string;
    boolOperator?: FilterExpressionBoolOperator;
    subExpression?: FilterExpressionList;
}
export namespace FilterExpressionData {
}


