/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FilterExpressionFieldWidgetType = {
    TextField: 'TEXT_FIELD',
    TextFieldChips: 'TEXT_FIELD_CHIPS',
    TextFieldNumber: 'TEXT_FIELD_NUMBER',
    TextFieldLookup: 'TEXT_FIELD_LOOKUP',
    TextBox: 'TEXT_BOX',
    Select: 'SELECT',
    SelectMultiple: 'SELECT_MULTIPLE',
    Date: 'DATE',
    Time: 'TIME',
    DateTime: 'DATE_TIME',
    CheckBox: 'CHECK_BOX',
    RadioButton: 'RADIO_BUTTON',
    Range: 'RANGE'
} as const;
export type FilterExpressionFieldWidgetType = typeof FilterExpressionFieldWidgetType[keyof typeof FilterExpressionFieldWidgetType];

