/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The order by object.. 
 */
export interface FilterExpressionOrderBy { 
    /**
     * The property name of the order by column.
     */
    propertyName?: string;
    order?: FilterExpressionOrderBy.OrderEnum;
}
export namespace FilterExpressionOrderBy {
    export const OrderEnum = {
        Asc: 'ASC',
        Desc: 'DESC'
    } as const;
    export type OrderEnum = typeof OrderEnum[keyof typeof OrderEnum];
}


