/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionDataType } from './filterExpressionDataType';


/**
 * The value of an expression operand. The type is named and the value itself is string formatted by the definition of the type. 
 */
export interface FilterExpressionOperandData { 
    /**
     * True if the given operand refers to property at the moment. The value as string is a property name.
     */
    isDataName?: boolean;
    valueAsString?: string;
    selectedValues: Array<string>;
    selectedObjects?: Array<object>;
    type?: FilterExpressionDataType;
}
export namespace FilterExpressionOperandData {
}


