/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchPageConfig } from './searchPageConfig';
import { SearchConfigHierarchyFilter } from './searchConfigHierarchyFilter';
import { UiActionDescriptor } from '../../view/model/uiActionDescriptor';


/**
 * This object has every configuration data that is necessary to open a SearchIndexResult page. It contains the possible filter expressions in a FilterExpresisonBuilderModel and also the parameterization of the result grid in a GridViewDescriptor object. 
 */
export interface SearchConfigHierarchy { 
    uri?: string;
    code?: string;
    searchConfig?: SearchPageConfig;
    filters: Array<SearchConfigHierarchyFilter>;
    actionDescriptor?: UiActionDescriptor;
}

