/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiActionDescriptor } from '../../view/model/uiActionDescriptor';
import { FilterExpressionList } from './filterExpressionList';


/**
 * Additional filter expression. 
 */
export interface SearchConfigHierarchyFilter { 
    code?: string;
    filterExpression?: FilterExpressionList;
    filters: Array<SearchConfigHierarchyFilter>;
    actionDescriptor?: UiActionDescriptor;
}

