/**
 * Filter API 2
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SmartFilterType = {
    Simple: 'SIMPLE',
    Advanced: 'ADVANCED'
} as const;
export type SmartFilterType = typeof SmartFilterType[keyof typeof SmartFilterType];

