/**
 * Session api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountInfo { 
    kind: string;
    userName: string;
    displayName: string;
    imageContent?: string;
    imageFormat?: string;
    roles?: Array<string>;
    parameters?: { [key: string]: string; };
}

