/**
 * Session api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountInfo } from './accountInfo';


export interface Session { 
    uri?: string;
    expiration?: string;
    /**
     * The expiration time of the current refresh token. If this time is over then the session is definetely invalid. 
     */
    refreshExpiration?: string;
    locale?: string;
    authentications: Array<AccountInfo>;
    user?: string;
    parameters: { [key: string]: string; };
    parameterClasses?: { [key: string]: string; };
    /**
     * ViewContexts in this session, URIs by UUID.
     */
    viewContexts: { [key: string]: string; };
    createdAt?: string;
}

