/**
 * Session api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountInfo } from './accountInfo';


export interface SessionInfoData { 
    sid: string;
    /**
     * The current refresh token.
     */
    refreshToken?: string;
    expiration?: string;
    /**
     * The lifetime of the refresh token in seconds. 
     */
    duration?: number;
    locale?: string;
    authentications?: Array<AccountInfo>;
    createdAt?: string;
}

