/**
 * Session api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * When a user executes an activity this entry is created based on the current session. It contains the information we know about the user and the time of the execution. The user is not necessarily user of the system so the user uri is optional and the user is a copied value from the session. 
 */
export interface UserActivityLog { 
    /**
     * The uri reference of the user.
     */
    userUri?: string;
    /**
     * The login name of the user.
     */
    userName?: string;
    /**
     * The role of the user.
     */
    role?: string;
    /**
     * The natural name of the user.
     */
    name?: string;
    timestamp?: string;
}

