/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenericValue { 
    /**
     * The uri the value.
     */
    uri?: string;
    /**
     * The logical code of the value.
     */
    code?: string;
    /**
     * The value as it is.
     */
    name?: string;
    /**
     * The description of the value if any. It is optional but can be usefull to have some idea about the given value. 
     */
    description?: string;
    /**
     * The code of icon that can be associatied with this value. It may be a uri.
     */
    icon?: string;
    /**
     * Indicates if this value is inactive.
     */
    inactive?: boolean;
}

