/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This enumeration defines the kinds of the transformation like MAPPING, RESOLVEBYMDM, CUSTOM etc.
 */
export const ValueTransformationKind = {
    Mapping: 'MAPPING',
    Resolvebymdm: 'RESOLVEBYMDM',
    Custom: 'CUSTOM'
} as const;
export type ValueTransformationKind = typeof ValueTransformationKind[keyof typeof ValueTransformationKind];

