/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This item is returned by the tranform methods. It contains the transformed value or the error code if any. 
 */
export interface ValueTransformationResult { 
    sourceValue?: object;
    transformedValue?: object;
    /**
     * The error about transforming the given value.
     */
    error?: string;
}

