/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvocationRequest } from '../../default';
import { ValueTransformationKind } from './valueTransformationKind';
import { ValueTransformationMappingItem } from './valueTransformationMappingItem';


/**
 * This object is a configuration to define the transformation from an input value set to an output value set. The transformation could be value mapping when the list of the values from the input are mapped one by one to the output values. This object is managed as a MDM entry in the platform. The ValueTransformationApi is using this MDM entry by default. If manage it by MDM then we enapsulate this object into a ValueTransformationConfig. 
 */
export interface ValueTransformationConfigData { 
    /**
     * The unique name of the transformation configuration. It matters only if it is managed by MDM.
     */
    name: string;
    kind?: ValueTransformationKind;
    mappings: Array<ValueTransformationMappingItem>;
    /**
     * If the kind is a resolution by MDM entry then this is the name of MDM definition.
     */
    mdmDefinition?: string;
    /**
     * If the kind is a resolution by MDM entry then this is the name of MDM entry inside the definition.
     */
    mdmEntry?: string;
    /**
     * If the kind is a resolution by MDM entry then this is the name of MDM entry inside the definition.
     */
    mdmPropertyName?: string;
    /**
     * If the transformation is too complex then a transformation InvocationRequest can be defined let it be script or api call. 
     */
    transformation?: InvocationRequest;
}
export namespace ValueTransformationConfigData {
}


