/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The mapping item contains a source value and a target value object pair. Even the source and the target could be object also. In this case we save the JSON object. 
 */
export interface ValueTransformationMappingItem { 
    sourceValue?: object;
    targetValue?: object;
}

