/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueSetDefinitionData } from './valueSetDefinitionData';


export interface ValueSetDefinition { 
    uri: string;
    data: ValueSetDefinitionData;
}

