/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueSetOperand } from './valueSetOperand';
import { ValueSetOperation } from './valueSetOperation';


export interface ValueSetExpression { 
    operation: ValueSetOperation;
    ignoreVersion: boolean;
    operands: Array<ValueSetOperand>;
}
export namespace ValueSetExpression {
}


