/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueSetExpression } from './valueSetExpression';
import { ValueSetDefinitionData } from './valueSetDefinitionData';


export interface ValueSetOperand { 
    /**
     * The namespace of the referred value set. 
     */
    namespace: string;
    /**
     * The name of the referred value set. 
     */
    name: string;
    data?: ValueSetDefinitionData;
    expression?: ValueSetExpression;
}

