/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ValueSetOperation = {
    Union: 'UNION',
    Intersect: 'INTERSECT',
    Dif: 'DIF',
    Symmetricdif: 'SYMMETRICDIF'
} as const;
export type ValueSetOperation = typeof ValueSetOperation[keyof typeof ValueSetOperation];

