/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValueSetDefinitionIdentifier { 
    /**
     * The namespace containing an arbitrary number of value sets. If it\'s null, the identifier refers to the global namespace. 
     */
    namespace?: string;
    /**
     * The unique name of the value set within its namespace. 
     */
    qualifiedName: string;
}

