/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Value { 
    /**
     * The uri the object of the value can be accessed.
     */
    objectUri?: string;
    /**
     * The logical code of the selectable value.
     */
    code?: string;
    /**
     * The string value that can be shown on ui. It might be a label code or the exact label.
     */
    displayValue?: string;
    /**
     * The code of icon that can be associatied with the value. It may be a uri.
     */
    iconCode?: string;
}

