/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueSetExpression } from './valueSetExpression';
import { ValueSetDefinitionKind } from './valueSetDefinitionKind';


export interface ValueSetDefinitionData { 
    kind: ValueSetDefinitionKind;
    /**
     * The logical name of the given value set. In case of an enum it is the fully qualified name of the enum class. 
     */
    qualifiedName: string;
    /**
     * The object definition of the value set.
     */
    objectDefinition?: string;
    /**
     * The fully qualified name of the type class.
     */
    typeClass?: string;
    /**
     * The name of the key property in the value. It will be the value that copied into the reference when a given item is selected from the value set. If it is not set then the default is the URI if it exists in the given object. Or it will be the code or id in this order. 
     */
    keyProperty?: string;
    /**
     * The name of the storage schema. Necessary to access the objects or the container (list or map).
     */
    storageSchema?: string;
    /**
     * The name of the list or map that contains the object uri list. It must be a unique name inside the storageSchema.
     */
    containerName?: string;
    /**
     * Optional icon code for the given value set.
     */
    iconCode?: string;
    /**
     * The value list that contains the value objects.
     */
    inlineValues?: Array<object>;
    /**
     * The list of keys. If we have this
     */
    keys?: Array<object>;
    expression?: ValueSetExpression;
}
export namespace ValueSetDefinitionData {
}


