/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterExpressionBuilderModel } from '../../filter/model/filterExpressionBuilderModel';
import { PropertyDefinitionData } from '../../default';


/**
 * The instance of the ValueSetDefintion that conatins every information inline. 
 */
export interface ValueSetData { 
    qualifiedName: string;
    /**
     * The name of the key property in the value. It will be the value that copied into the reference when a given item is selected from the value set. 
     */
    keyProperty?: string;
    properties: Array<PropertyDefinitionData>;
    /**
     * Optional icon code for the given value set.
     */
    iconCode?: string;
    /**
     * If true then the value set is not defined and not accessible. 
     */
    undefined?: boolean;
    /**
     * If true then the values doesn\'t contains the the whole values set or it migth be empty and we have to ask for filtered set of values using the filter fields available. 
     */
    lazy?: boolean;
    values: Array<object>;
    /**
     * The filter expression model for the search from values.
     */
    filterModel?: FilterExpressionBuilderModel;
}

