/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ValueSetDefinitionKind = {
    Enum: 'ENUM',
    Inline: 'INLINE',
    List: 'LIST',
    Map: 'MAP',
    Allof: 'ALLOF',
    Setof: 'SETOF',
    Searchindexbased: 'SEARCHINDEXBASED',
    Composite: 'COMPOSITE',
    Undefined: 'UNDEFINED'
} as const;
export type ValueSetDefinitionKind = typeof ValueSetDefinitionKind[keyof typeof ValueSetDefinitionKind];

