/**
 * value api
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueTransformationConfigData } from './valueTransformationConfigData';


/**
 * This object is a configuration to define the transformation from an input value set to an output value set. The transformation could be value mapping when the list of the values from the input are mapped one by one to the output values. This object is managed as a MDM entry in the platform. The ValueTransformationApi is using this MDM entry by default. It has a data inline object that contains configuration itself. 
 */
export interface ValueTransformationConfig { 
    uri: string;
    data?: ValueTransformationConfigData;
}

