/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ComponentType = {
    Container: 'container',
    Form: 'form',
    Widget: 'widget'
} as const;
export type ComponentType = typeof ComponentType[keyof typeof ComponentType];

