/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ComponentWidgetType = {
    Grid: 'grid',
    Filter: 'filter',
    Tree: 'tree',
    Toolbar: 'toolbar'
} as const;
export type ComponentWidgetType = typeof ComponentWidgetType[keyof typeof ComponentWidgetType];

