/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmartComponentLayoutDefinition } from './smartComponentLayoutDefinition';
import { ViewConstraint } from '../../view/model/viewConstraint';


export interface LayoutDefinitionDescriptor { 
    uri?: string;
    name?: string;
    layout?: SmartComponentLayoutDefinition;
    constraint?: ViewConstraint;
}

