/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LayoutDirection = {
    Horizontal: 'horizontal',
    Vertical: 'vertical'
} as const;
export type LayoutDirection = typeof LayoutDirection[keyof typeof LayoutDirection];

