/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentWidgetType } from './componentWidgetType';
import { FilterExpressionFieldList } from '../../filter/model/filterExpressionFieldList';
import { SmartFilterType } from '../../filter/model/smartFilterType';


export interface SmartComponentWidgetDefinition {
    type: ComponentWidgetType;
    identifier?: string;
    filterExpressionFieldList?: FilterExpressionFieldList;
    filterType?: SmartFilterType;
}
export namespace SmartComponentWidgetDefinition {
}


