/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentType } from './componentType';
import { LayoutDirection } from './layoutDirection';
import { SmartComponentWidgetDefinition } from './smartComponentWidgetDefinition';
import { Style } from '../../view/model/style';
import { SmartWidgetDefinition } from '../../form/model/smartWidgetDefinition';


export interface SmartComponentLayoutDefinition { 
    /**
     * An optional identifier to find this element in a layout hierarchy. 
     */
    identifier?: string;
    type: ComponentType;
    expandable?: boolean;
    expandableSectionLabel?: string;
    direction?: LayoutDirection;
    components?: Array<SmartComponentLayoutDefinition>;
    widget?: SmartComponentWidgetDefinition;
    form?: Array<SmartWidgetDefinition>;
    style?: Style;
}
export namespace SmartComponentLayoutDefinition {
}


