openapi: 3.0.1
info:
  title: Form layout definition
  description: Contains form layout definition objects.
  termsOfService: ""
  contact:
    email: info@it4all.hu
  version: 1.0.0
tags:
  - name: FormLayoutDefinition
paths:
  /nope:
    post:
      summary: Placeholder for generation
      responses:
        "200":
          description: nope
components:
  schemas:
    SmartComponentLayoutDefinition:
      type: object
      required:
        - type
      properties:
        identifier:
          type: string
          description: |
            An optional identifier to find this element in a layout hierarchy.
        type:
          $ref: "#/components/schemas/ComponentType"
        expandable:
          type: boolean
        expandableSectionLabel:
          type: string
        direction:
          $ref: "#/components/schemas/LayoutDirection"
        components:
          type: array
          items:
            $ref: "#/components/schemas/SmartComponentLayoutDefinition"
        widget:
          $ref: "#/components/schemas/SmartComponentWidgetDefinition"
        form:
          type: array
          items:
            type: SmartWidgetDefinition
        style:
          type: Style
    SmartComponentWidgetDefinition:
      type: object
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/ComponentWidgetType"
        identifier:
          type: string
        filterExpressionFieldList:
          type: FilterExpressionFieldList
        filterType:
          type: SmartFilterType
    LayoutDirection:
      type: string
      enum:
        - horizontal
        - vertical
    ComponentType:
      type: string
      enum:
        - container
        - form
        - widget
    ComponentWidgetType:
      type: string
      enum:
        - grid
        - filter
        - tree
        - toolbar
    LayoutDefinitionDescriptor:
      type: object
      properties:
        uri:
          type: string
          format: uri
        name:
          type: string
        layout:
          $ref: "#/components/schemas/SmartComponentLayoutDefinition"
        constraint:
          type: ViewConstraint
