/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Text or media content the client should copy to its system\'s clipboard. 
 */
export interface ClipboardData { 
    /**
     * The raw text to copy to clipboard. 
     */
    text?: string;
}

