/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CloseResult = {
    Approved: 'approved',
    Pending: 'pending',
    Rejected: 'rejected'
} as const;
export type CloseResult = typeof CloseResult[keyof typeof CloseResult];

