/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamedValidator } from './namedValidator';
import { ValueSetData } from '../../value/model/valueSetData';


/**
 * The component constraint is responsible for the constraints belong to a given component (textfield, combobox etc.) on the view. The UI must identify the component by the dataName that is a path of the data name separated by dot like dataSheet.field. 
 */
export interface ComponentConstraint { 
    /**
     * The data name to identify the related component or componenets. If it is a path the format is the following - dataSheet.field.
     */
    dataName?: string;
    visible?: boolean;
    mandatory?: boolean;
    enabled?: boolean;
    valueSet?: ValueSetData;
    min?: number;
    max?: number;
    minLength?: number;
    maxLength?: number;
    namedValidators: Array<NamedValidator>;
}

