/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Change of a ComponentModel. 
 */
export interface ComponentModelChange { 
    uuid: string;
    path: string;
    value?: object;
    /**
     * Changed values, in a key-value map. Refers to different parts of ComponentModel, for example  data changes are prefixed with \'data.\', layout changes with \'layouts.\', etc. 
     */
    changes: { [key: string]: any; };
    /**
     * List of changed widgets (widgetIds).
     */
    changedWidgets?: Array<string>;
}

