/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmartLayoutDefinition } from '../../form/model/smartLayoutDefinition';
import { ComponentConstraint } from './componentConstraint';
import { SmartComponentLayoutDefinition } from '../../scld/model/smartComponentLayoutDefinition';
import { Style } from './style';
import { UiAction } from './uiAction';
import { ValueSet } from './valueSet';


/**
 * Model of a UI component. Contains all information in one object, which are needed  to render a fully functionin component. 
 */
export interface ComponentModel { 
    uuid: string;
    name: string;
    data?: object;
    constraints: Array<ComponentConstraint>;
    layouts: { [key: string]: SmartLayoutDefinition; };
    componentLayouts?: { [key: string]: SmartComponentLayoutDefinition; };
    actions: Array<UiAction>;
    valueSets?: { [key: string]: ValueSet; };
    /**
     * List of widgets (widgetIds).
     */
    widgets?: Array<string>;
    style?: Style;
    parentStyle?: Style;
}

