/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataChangeKind } from './dataChangeKind';


export interface DataChange { 
    kind?: DataChangeKind;
    /**
     * Source of the event, typically the key of the widget.
     */
    source?: string;
    /**
     * Changed values, in a key-value map.
     */
    values?: { [key: string]: any; };
}
export namespace DataChange {
}


