/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the kind of the source of this event.. 
 */
export const DataChangeKind = {
    Widget: 'WIDGET',
    Selection: 'SELECTION',
    Lookup: 'LOOKUP'
} as const;
export type DataChangeKind = typeof DataChangeKind[keyof typeof DataChangeKind];

