/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataChangeKind } from './dataChangeKind';


export interface DataChangeEvent { 
    kind?: DataChangeKind;
    /**
     * Source of the event, typically the key of the widget.
     */
    source?: string;
    /**
     * Values before changed, in a key-value map.
     */
    oldValues?: { [key: string]: any; };
    /**
     * Values before changed, in a key-value map.
     */
    newValues?: { [key: string]: any; };
}
export namespace DataChangeEvent {
}


