/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information of the device running the current view context.
 */
export interface DeviceInfo { 
    /**
     * Unique identifier of the client\'s device. E.g.: android_id. 
     */
    deviceId: string;
    /**
     * The type of the device. E.g.: browser, android, iOS or else.  This information is not required and should be used with caution since the clients may  define their own type differently. 
     */
    deviceType?: string;
    /**
     * The user-agent information from the client.
     */
    userAgent?: string;
    /**
     * IP address of the client.
     */
    ipAddress?: string;
    /**
     * Any additional parameters that the client may share with the server.
     */
    parameters: { [key: string]: any; };
}

