/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about uploaded file. 
 */
export interface DownloadedFile { 
    uuid?: string;
    identifier?: string;
    filename?: string;
}

