/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the position of an icon related to the button\'s label. 
 */
export const IconPosition = {
    Pre: 'PRE',
    Post: 'POST'
} as const;
export type IconPosition = typeof IconPosition[keyof typeof IconPosition];

