/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiActionTooltip } from './uiActionTooltip';
import { Style } from './style';


export interface ImageResource { 
    kind?: ImageResource.KindEnum;
    source?: string;
    identifier?: string;
    color?: string;
    style?: Style;
    tooltip?: UiActionTooltip;
}
export namespace ImageResource {
    export const KindEnum = {
        Fe: 'FE',
        Be: 'BE',
        Url: 'URL'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


