/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An anchor with a href representing a hyperlink object, which the client will open.  For possible attributes see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a 
 */
export interface Link { 
    /**
     * The URL that this link points to. It will be anchor\'s href attribute\'s value.
     */
    url: string;
    /**
     * Specifies if created anchor should contain download attribute.
     */
    download?: boolean;
    /**
     * Used only when download is true, it will download attribute\'s value
     */
    filename?: string;
    target?: Link.TargetEnum;
}
export namespace Link {
    export const TargetEnum = {
        Self: 'SELF',
        Blank: 'BLANK',
        Parent: 'PARENT',
        Top: 'TOP'
    } as const;
    export type TargetEnum = typeof TargetEnum[keyof typeof TargetEnum];
}


