/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MessageType = {
    Info: 'info',
    Question: 'question',
    Warning: 'warning',
    Error: 'error'
} as const;
export type MessageType = typeof MessageType[keyof typeof MessageType];

