/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MessageTextType = {
    Plain: 'plain',
    Html: 'html'
} as const;
export type MessageTextType = typeof MessageTextType[keyof typeof MessageTextType];

