/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const MessageOptionType = {
    Confirm: 'confirm',
    Reject: 'reject',
    Cancel: 'cancel'
} as const;
export type MessageOptionType = typeof MessageOptionType[keyof typeof MessageOptionType];

