/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageOption } from './messageOption';
import { MessageTextType } from './messageTextType';
import { MessageType } from './messageType';


export interface MessageData { 
    /**
     * Unique identifier of the Message.
     */
    uuid: string;
    /**
     * UUID of the View, showing this message. May be null.
     */
    viewUuid?: string;
    type: MessageType;
    header?: string;
    text?: string;
    textType?: MessageTextType;
    options?: Array<MessageOption>;
}
export namespace MessageData {
}


