/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageOption } from './messageOption';


export interface MessageResult { 
    selectedOption: MessageOption;
    additionalData?: object;
}

