/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NamedValidator { 
    name: string;
    params: { [key: string]: object; };
    /**
     * ADD:     REMOVE:  ALTER:  Do not explicitly add, but alter preexisting matching validator\'s parameters 
     */
    operation: NamedValidator.OperationEnum;
}
export namespace NamedValidator {
    export const OperationEnum = {
        Add: 'ADD',
        Remove: 'REMOVE',
        Alter: 'ALTER'
    } as const;
    export type OperationEnum = typeof OperationEnum[keyof typeof OperationEnum];
}


