/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CloseResult } from './closeResult';
import { View } from './view';


/**
 * All information regarding opening a view (and possible it\'s parents).
 */
export interface OpenPendingData { 
    viewsToOpen: Array<string>;
    viewsToClose: Array<string>;
    results: { [key: string]: CloseResult; };
    /**
     * This map holds the \'used\' closed children which should be restored on reject.
     */
    closedChildren: { [key: string]: View; };
}

