/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ServerRequestType = {
    Action: 'ACTION',
    WidgetAction: 'WIDGET_ACTION',
    CreateViewContext: 'CREATE_VIEW_CONTEXT',
    UpdateViewContext: 'UPDATE_VIEW_CONTEXT',
    GetViewContext: 'GET_VIEW_CONTEXT',
    HandleMessageResult: 'HANDLE_MESSAGE_RESULT',
    ShowSmartlink: 'SHOW_SMARTLINK',
    Download: 'DOWNLOAD',
    GetComponentModel: 'GET_COMPONENT_MODEL'
} as const;
export type ServerRequestType = typeof ServerRequestType[keyof typeof ServerRequestType];

