/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { View } from './view';


/**
 * Represents a stored smartlink. Contains identifiers and a View, which will be opened,  when this smartlink is clicked. 
 */
export interface SmartLinkData { 
    uri?: string;
    uuid?: string;
    view?: View;
    url?: string;
    /**
     * If the user who clicked the link, is not part of the acl, an error page will open.
     */
    acl?: string;
}

