/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Style data holder for client
 */
export interface Style { 
    style: { [key: string]: string; };
    classesToAdd: Array<string>;
    classesToRemove: Array<string>;
}

