/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const UiActionInputType = {
    None: 'none',
    Textfield: 'textfield',
    Textarea: 'textarea',
    UserSelect: 'user_select',
    File: 'file',
    MultipleFiles: 'multiple_files'
} as const;
export type UiActionInputType = typeof UiActionInputType[keyof typeof UiActionInputType];

