/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiActionTooltip } from './uiActionTooltip';
import { IconPosition } from './iconPosition';
import { UiActionFeedbackType } from './uiActionFeedbackType';
import { UiActionDialogDescriptor } from './uiActionDialogDescriptor';
import { UiActionUploadDescriptor } from './uiActionUploadDescriptor';
import { UiActionButtonType } from './uiActionButtonType';


/**
 * Describes the appearance (as a button) and the properties of the related dialogs of a UiAction. 
 */
export interface UiActionDescriptor { 
    title: string;
    type: UiActionButtonType;
    color: string;
    icon?: string;
    iconColor?: string;
    iconPosition?: IconPosition;
    dialog?: UiActionDialogDescriptor;
    confirmDialog?: UiActionDialogDescriptor;
    inputDialog?: UiActionDialogDescriptor;
    input2Dialog?: UiActionDialogDescriptor;
    feedbackType?: UiActionFeedbackType;
    feedbackText?: string;
    upload?: UiActionUploadDescriptor;
    tooltip?: UiActionTooltip;
}
export namespace UiActionDescriptor {
}


