/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the type of the button. 
 */
export const UiActionButtonType = {
    Normal: 'NORMAL',
    Flat: 'FLAT',
    Stroked: 'STROKED',
    Raised: 'RAISED',
    Icon: 'ICON',
    MiniFab: 'MINI_FAB',
    Fab: 'FAB',
    Separator: 'SEPARATOR',
    Submenu: 'SUBMENU'
} as const;
export type UiActionButtonType = typeof UiActionButtonType[keyof typeof UiActionButtonType];

