/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UiActionTooltip { 
    tooltip?: string;
    tooltipPosition?: UiActionTooltip.TooltipPositionEnum;
    tooltipDelay?: number;
    tooltipHideDelay?: number;
}
export namespace UiActionTooltip {
    export const TooltipPositionEnum = {
        After: 'AFTER',
        Before: 'BEFORE',
        Above: 'ABOVE',
        Below: 'BELOW',
        Left: 'LEFT',
        Right: 'RIGHT'
    } as const;
    export type TooltipPositionEnum = typeof TooltipPositionEnum[keyof typeof TooltipPositionEnum];
}


