/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiActionTooltip } from './uiActionTooltip';
import { IconPosition } from './iconPosition';


/**
 * Describes a button which is presented on the UiAction dialog. 
 */
export interface UiActionButtonDescriptor { 
    caption: string;
    color: string;
    icon?: string;
    iconColor?: string;
    iconPosition?: IconPosition;
    tooltip?: UiActionTooltip;
    cssClass?: string;
}
export namespace UiActionButtonDescriptor {
}


