/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the possible feedback types which are shown if a UiAction was completed. 
 */
export const UiActionFeedbackType = {
    None: 'NONE',
    Snackbar: 'SNACKBAR'
} as const;
export type UiActionFeedbackType = typeof UiActionFeedbackType[keyof typeof UiActionFeedbackType];

