/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The UiAction constraint is responsible for the constraints belong to a given action (button, menu option etc.) on the view. The UI must identify the action by the dataName that is a path of the data name separated by dot like dataSheet.field. 
 */
export interface UiActionConstraint { 
    /**
     * The path format is the following - dataSheet.actionCode.
     */
    path?: string;
    visible?: boolean;
    enabled?: boolean;
}

