/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A request to perform user action initiated on the client interface
 */
export interface UiActionRequest { 
    /**
     * Code of the executed UI action.
     */
    code: string;
    path?: string;
    /**
     * Identifier of UI element, or UI action, where action is performed (for example treeNode\'s /  listItem\'s identifier, etc.). Optional. 
     */
    identifier?: string;
    /**
     * Additional parameters for executing the UI action. 
     */
    params: { [key: string]: any; };
}

