/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UiActionInputType } from './uiActionInputType';
import { UiActionDescriptor } from './uiActionDescriptor';


export interface UiAction { 
    code?: string;
    path?: string;
    identifier?: string;
    inputType?: UiActionInputType;
    input2Type?: UiActionInputType;
    /**
     * If true, UiAction will submit the form (causing validation) and sends model in UiActionRequest.
     */
    submit?: boolean;
    /**
     * If true, UiAction will NOT submit the form and sends model WITHOUT VALIDATION in UiActionRequest.
     */
    model?: boolean;
    confirm?: boolean;
    /**
     * Additional parameters for executing the UI action. 
     */
    params?: { [key: string]: any; };
    descriptor?: UiActionDescriptor;
    /**
     * The sub action are set if and only if this action is a sub menu. The sub actions can be null.
     */
    subActions?: Array<UiAction>;
    /**
     * The id of toolbar which this UiAction should be placed on.
     */
    toolbar?: string;
    /**
     * Whether this action should appear disabled or not.
     */
    disabled?: boolean;
}
export namespace UiAction {
}


