/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes the look of an upload component that is related to a specific UiAction. 
 */
export interface UiActionUploadDescriptor { 
    title: string;
    description?: string;
    maxSize?: string;
    formats?: string;
    uploadButtonTitle?: string;
    backgroundColour?: string;
    textColour?: string;
}

