/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BinaryData } from '../../default';


/**
 * Information about uploaded file. 
 */
export interface UploadedFile { 
    filename?: string;
    size?: number;
    data?: BinaryData;
}

