/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValueSetData } from '../../value/model/valueSetData';


/**
 * An instance of a ValueSetData tied together with a logical timestamp (counter). It can be used  as a request item, without specifying valueSetData, 
 */
export interface ValueSet { 
    valueSetName?: string;
    valueSetData?: ValueSetData;
    timestamp?: number;
}

