/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This object is a placeholder for the view, typically for closed children views  so these are not saved in ViewContext object, keeping it\'s size reasonable. 
 */
export interface ViewPlaceholder { 
    /**
     * Unique identifier of the View.
     */
    uuid?: string;
    closedChildrenViews: Array<ViewPlaceholder>;
}

