/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerRequestTrack } from './serverRequestTrack';
import { DownloadedFile } from './downloadedFile';
import { OpenPendingData } from './openPendingData';
import { ClipboardData } from './clipboardData';
import { DeviceInfo } from './deviceInfo';
import { View } from './view';
import { Link } from './link';


/**
 * The same session can be valid / used in multiple UIs, this object represents a UI.
 */
export interface ViewContext { 
    uri: string;
    uuid?: string;
    views: Array<View>;
    links: Array<Link>;
    downloads: Array<DownloadedFile>;
    clipboardData?: Array<ClipboardData>;
    openPendingData?: OpenPendingData;
    currentRequest?: ServerRequestTrack;
    deviceInfo?: DeviceInfo;
}

