/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentModelChange } from './componentModelChange';
import { ViewContextData } from './viewContextData';


/**
 * The same session can be valid / used in multiple UIs, this object represents a UI.
 */
export interface ViewContextChange { 
    viewContext: ViewContextData;
    changes: Array<ComponentModelChange>;
    /**
     * If the server call is wrapped inside this ViewContextChange, then this field will contain the result of the original call. 
     */
    result?: object;
}

