/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewStateUpdate } from './viewStateUpdate';
import { DeviceInfo } from './deviceInfo';


/**
 * State update of a ViewContext.
 */
export interface ViewContextUpdate { 
    /**
     * ViewContext\'s unique identifier.
     */
    uuid?: string;
    updates?: Array<ViewStateUpdate>;
    deviceInfo?: DeviceInfo;
}

