/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageData } from './messageData';
import { ViewState } from './viewState';
import { ViewType } from './viewType';


export interface ViewData { 
    /**
     * Unique identifier of the View.
     */
    uuid: string;
    viewName: string;
    message?: MessageData;
    state: ViewState;
    type: ViewType;
    containerUuid?: string;
}
export namespace ViewData {
}


