/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentConstraint } from './componentConstraint';


/**
 * The view constraint object encapsulate the constraints can be applied to any view genericly. It consists of compenet constraints and many more. 
 */
export interface ViewConstraint { 
    componentConstraints: Array<ComponentConstraint>;
}

