/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ViewType = {
    Normal: 'normal',
    Dialog: 'dialog',
    Embedded: 'embedded'
} as const;
export type ViewType = typeof ViewType[keyof typeof ViewType];

