/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ViewState = {
    OpenPending: 'open_pending',
    ToOpen: 'to_open',
    Opened: 'opened',
    ClosePending: 'close_pending',
    CloseApproved: 'close_approved',
    ToClose: 'to_close',
    Closed: 'closed'
} as const;
export type ViewState = typeof ViewState[keyof typeof ViewState];

