/**
 * View API
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewState } from './viewState';


/**
 * State update of a view.
 */
export interface ViewStateUpdate { 
    /**
     * ViewContext\'s unique identifier.
     */
    uuid?: string;
    state?: ViewState;
}
export namespace ViewStateUpdate {
}


