/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mapping of two properties.
 */
export interface PropertyMapping { 
    /**
     * Property name in the data model. This will be saved.
     */
    data?: string;
    /**
     * Property name in the selection model. This will won\'t be saved here, we use it for selection.
     */
    selection?: string;
}

