/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PropertyMapping } from './propertyMapping';


/**
 * The definition of an arbitrary selection.
 */
export interface SelectionDefinition { 
    /**
     * Name of the ValueSet used for this selection.
     */
    valueSetName: string;
    /**
     * Defines how the selection should work: for properties or the whole selected Object. 
     */
    type: SelectionDefinition.TypeEnum;
    /**
     * Specifies which property from ValueSetData.values as Object should be used in  selection widget. 
     */
    displayProperty?: string;
    /**
     * Mapping between data and selection model. It may be possible to omit mapping, in this case the default mapping is: data = widget.key, selection = valueSetData.keyProperty 
     */
    mapping: Array<PropertyMapping>;
    /**
     * Optional value, used for empty valueList entry, this will be the label.
     */
    emptyLabel?: string;
}
export namespace SelectionDefinition {
    export const TypeEnum = {
        Property: 'PROPERTY',
        Object: 'OBJECT'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


