/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SmartFormWidgetType = {
    CheckBox: 'CHECK_BOX',
    CheckBox2: 'CHECK_BOX_2',
    Container: 'CONTAINER',
    DatePicker: 'DATE_PICKER',
    DateTimePicker: 'DATE_TIME_PICKER',
    Indicator: 'INDICATOR',
    Item: 'ITEM',
    ItemGroup: 'ITEM_GROUP',
    Label: 'LABEL',
    RadioButton: 'RADIO_BUTTON',
    Select: 'SELECT',
    SelectMultiple: 'SELECT_MULTIPLE',
    TextBox: 'TEXT_BOX',
    TextField: 'TEXT_FIELD',
    TextFieldChips: 'TEXT_FIELD_CHIPS',
    TextFieldNumber: 'TEXT_FIELD_NUMBER',
    TextFieldLookup: 'TEXT_FIELD_LOOKUP',
    Time: 'TIME',
    Toggle: 'TOGGLE',
    Image: 'IMAGE',
    FileUploader: 'FILE_UPLOADER',
    Media: 'MEDIA',
    Button: 'BUTTON',
    Divider: 'DIVIDER',
    Component: 'COMPONENT',
    RichText: 'RICH_TEXT',
    Sortable: 'SORTABLE',
    Matrix: 'MATRIX',
    MonthPicker: 'MONTH_PICKER',
    YoutubePlayer: 'YOUTUBE_PLAYER',
    Svg: 'SVG'
} as const;
export type SmartFormWidgetType = typeof SmartFormWidgetType[keyof typeof SmartFormWidgetType];

