/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SmartFormInputMode = {
    None: 'NONE',
    Url: 'URL',
    Search: 'SEARCH',
    Numeric: 'NUMERIC',
    Tel: 'TEL',
    Decimal: 'DECIMAL',
    Email: 'EMAIL'
} as const;
export type SmartFormInputMode = typeof SmartFormInputMode[keyof typeof SmartFormInputMode];

