/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmartWidgetHint { 
    text?: string;
    position?: SmartWidgetHint.PositionEnum;
}
export namespace SmartWidgetHint {
    export const PositionEnum = {
        UnderLabel: 'UNDER_LABEL',
        UnderInput: 'UNDER_INPUT'
    } as const;
    export type PositionEnum = typeof PositionEnum[keyof typeof PositionEnum];
}


