/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SmartWidgetDefinition } from './smartWidgetDefinition';


export interface SmartLayoutDefinition { 
    widgets: Array<SmartWidgetDefinition>;
}

