/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const SmartFormWidgetDirection = {
    Col: 'COL',
    Row: 'ROW'
} as const;
export type SmartFormWidgetDirection = typeof SmartFormWidgetDirection[keyof typeof SmartFormWidgetDirection];

