/**
 * Form layout definition
 *
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This enum defines the value change handling strategy. Currently only one method is supported, IMMEDIATE_ACTION, which will trigger an executeUiAction when the value is changed. 
 */
export const ValueChangeMode = {
    None: 'NONE',
    ImmediateAction: 'IMMEDIATE_ACTION'
} as const;
export type ValueChangeMode = typeof ValueChangeMode[keyof typeof ValueChangeMode];

